name: "CI"

on: [push, pull_request]
defaults:
  run:
    working-directory: ./backend/

jobs:
    test:
      name: test
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
              npm install
              npm run test
    
    lint:
      name: lint
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
              npm install
              npm run lint
